In [214]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [215]:
df=pd.read_csv("train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [216]:
df_test=pd.read_csv("test.csv")
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [217]:
df.shape

(891, 12)

In [218]:
df_test.shape

(418, 11)

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [220]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [221]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [222]:
df.drop(["Cabin"],axis=1,inplace=True)
df_test.drop(["Cabin"],axis=1,inplace=True)

In [223]:
df.drop(["Name"],axis=1,inplace=True)
df_test.drop(["Name"],axis=1,inplace=True)
df.drop(["Ticket"],axis=1,inplace=True)
df_test.drop(["Ticket"],axis=1,inplace=True)

In [224]:
df.drop(["PassengerId"],axis=1,inplace=True)

In [225]:
from sklearn.impute import KNNImputer
knn_imputer = KNNImputer(n_neighbors=5)
df["Age"]=knn_imputer.fit_transform(df[["Age"]])
df_test["Age"]=knn_imputer.fit_transform(df_test[["Age"]])

In [226]:
df_test["Fare"]=knn_imputer.fit_transform(df_test[["Fare"]])

In [227]:
df.dropna(inplace=True)

In [228]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [229]:
df_test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [230]:
df

Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[889 rows x 8 columns]

In [231]:
df["Embarked"].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [232]:
#from sklearn.preprocessing import OneHotEncoder
#encoder=OneHotEncoder(drop="first")
#encoded =encoder.fit_transform(df[['Embarked']])
#encoded_df = pd.DataFrame(encoded.toarray(), columns=["embarked_1","embarked_2"])
#df = pd.concat([df, encoded_df], axis=1)

In [233]:
#encoded2 =encoder.fit_transform(df_test[['Embarked']])
#encoded_df = pd.DataFrame(encoded2.toarray(), columns=["embarked_1","embarked_2"])
#df_test = pd.concat([df_test, encoded_df], axis=1)

In [234]:
emb=pd.get_dummies(df["Embarked"],drop_first=True)
df=pd.concat([df,emb],axis=1)
emb_=pd.get_dummies(df_test["Embarked"],drop_first=True)
df_test=pd.concat([df_test,emb_],axis=1)

In [235]:
df.drop(["Embarked"],axis=1,inplace=True)
df_test.drop(["Embarked"],axis=1,inplace=True)

In [236]:
pclass=pd.get_dummies(df["Pclass"],drop_first=True)
df=pd.concat([df,pclass],axis=1)
p_class=pd.get_dummies(df_test["Pclass"],drop_first=True)
df_test=pd.concat([df_test,p_class],axis=1)

In [237]:
df.drop(["Pclass"],axis=1,inplace=True)
df_test.drop(["Pclass"],axis=1,inplace=True)

In [238]:
df

Survived     Sex        Age  SibSp  Parch     Fare  Q  S  2  3
0           0    male  22.000000      1      0   7.2500  0  1  0  1
1           1  female  38.000000      1      0  71.2833  0  0  0  0
2           1  female  26.000000      0      0   7.9250  0  1  0  1
3           1  female  35.000000      1      0  53.1000  0  1  0  0
4           0    male  35.000000      0      0   8.0500  0  1  0  1
..        ...     ...        ...    ...    ...      ... .. .. .. ..
886         0    male  27.000000      0      0  13.0000  0  1  1  0
887         1  female  19.000000      0      0  30.0000  0  1  0  0
888         0  female  29.699118      1      2  23.4500  0  1  0  1
889         1    male  26.000000      0      0  30.0000  0  0  0  0
890         0    male  32.000000      0      0   7.7500  1  0  0  1

[889 rows x 10 columns]

In [239]:
df.isnull().sum()

Survived    0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Q           0
S           0
2           0
3           0
dtype: int64

In [240]:
df_test

PassengerId     Sex       Age  SibSp  Parch      Fare  Q  S  2  3
0            892    male  34.50000      0      0    7.8292  1  0  0  1
1            893  female  47.00000      1      0    7.0000  0  1  0  1
2            894    male  62.00000      0      0    9.6875  1  0  1  0
3            895    male  27.00000      0      0    8.6625  0  1  0  1
4            896  female  22.00000      1      1   12.2875  0  1  0  1
..           ...     ...       ...    ...    ...       ... .. .. .. ..
413         1305    male  30.27259      0      0    8.0500  0  1  0  1
414         1306  female  39.00000      0      0  108.9000  0  0  0  0
415         1307    male  38.50000      0      0    7.2500  0  1  0  1
416         1308    male  30.27259      0      0    8.0500  0  1  0  1
417         1309    male  30.27259      1      1   22.3583  0  0  0  1

[418 rows x 10 columns]

In [241]:
mapping={"male":0,"female":1}
df["Sex"]=df["Sex"].map(mapping)
df_test["Sex"]=df_test["Sex"].map(mapping)

In [242]:
df_test

PassengerId  Sex       Age  SibSp  Parch      Fare  Q  S  2  3
0            892    0  34.50000      0      0    7.8292  1  0  0  1
1            893    1  47.00000      1      0    7.0000  0  1  0  1
2            894    0  62.00000      0      0    9.6875  1  0  1  0
3            895    0  27.00000      0      0    8.6625  0  1  0  1
4            896    1  22.00000      1      1   12.2875  0  1  0  1
..           ...  ...       ...    ...    ...       ... .. .. .. ..
413         1305    0  30.27259      0      0    8.0500  0  1  0  1
414         1306    1  39.00000      0      0  108.9000  0  0  0  0
415         1307    0  38.50000      0      0    7.2500  0  1  0  1
416         1308    0  30.27259      0      0    8.0500  0  1  0  1
417         1309    0  30.27259      1      1   22.3583  0  0  0  1

[418 rows x 10 columns]

In [243]:
x=df.iloc[:,1:].values
y=df.iloc[:,1].values

In [251]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.1)

In [185]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [252]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()
model1.fit(x_train,y_train)
y_pred=model1.predict(x_test)

C:\Users\SAJJAD-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [253]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

1.0


In [254]:
from sklearn.svm import SVC
model2=SVC(kernel="linear")
model2.fit(x_train,y_train)
y_pred=model2.predict(x_test)

In [255]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

1.0


In [249]:
from sklearn.tree import DecisionTreeClassifier
model3=DecisionTreeClassifier(criterion="entropy")
model3.fit(x_train,y_train)
y_pred=model3.predict(x_test)

In [250]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

1.0


In [208]:
df_test

PassengerId  Sex       Age  SibSp  Parch      Fare  Q  S  2  3  Survived
0            892    0  34.50000      0      0    7.8292  1  0  0  1         0
1            893    1  47.00000      1      0    7.0000  0  1  0  1         1
2            894    0  62.00000      0      0    9.6875  1  0  1  0         0
3            895    0  27.00000      0      0    8.6625  0  1  0  1         0
4            896    1  22.00000      1      1   12.2875  0  1  0  1         1
..           ...  ...       ...    ...    ...       ... .. .. .. ..       ...
413         1305    0  30.27259      0      0    8.0500  0  1  0  1         0
414         1306    1  39.00000      0      0  108.9000  0  0  0  0         1
415         1307    0  38.50000      0      0    7.2500  0  1  0  1         0
416         1308    0  30.27259      0      0    8.0500  0  1  0  1         0
417         1309    0  30.27259      1      1   22.3583  0  0  0  1         0

[418 rows x 11 columns]

In [196]:
x_df_test=df_test.iloc[:,1:].values

In [197]:
x_df_test=sc.transform(x_df_test)

In [209]:
df_test["Survived"]=model3.predict(x_df_test)

In [210]:
df_test

PassengerId  Sex       Age  SibSp  Parch      Fare  Q  S  2  3  Survived
0            892    0  34.50000      0      0    7.8292  1  0  0  1         0
1            893    1  47.00000      1      0    7.0000  0  1  0  1         1
2            894    0  62.00000      0      0    9.6875  1  0  1  0         0
3            895    0  27.00000      0      0    8.6625  0  1  0  1         0
4            896    1  22.00000      1      1   12.2875  0  1  0  1         1
..           ...  ...       ...    ...    ...       ... .. .. .. ..       ...
413         1305    0  30.27259      0      0    8.0500  0  1  0  1         0
414         1306    1  39.00000      0      0  108.9000  0  0  0  0         1
415         1307    0  38.50000      0      0    7.2500  0  1  0  1         0
416         1308    0  30.27259      0      0    8.0500  0  1  0  1         0
417         1309    0  30.27259      1      1   22.3583  0  0  0  1         0

[418 rows x 11 columns]

In [211]:
result_titanic=df_test[["PassengerId","Survived"]]

In [212]:
result_titanic

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [213]:
result_titanic.to_csv('titanic_results.csv', index=False)

In [256]:
x_train

array([[ 1.        , 29.69911765,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        , 22.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        , 33.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        , 29.69911765,  0.        , ...,  1.        ,
         0.        ,  1.        ],
       [ 0.        , 56.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.        , 17.        ,  0.        , ...,  1.        ,
         0.        ,  1.        ]])

In [257]:
x_test

array([[  0.        ,  22.        ,   0.        ,   0.        ,
          7.225     ,   0.        ,   0.        ,   0.        ,
          1.        ],
       [  0.        ,  59.        ,   0.        ,   0.        ,
          7.25      ,   0.        ,   1.        ,   0.        ,
          1.        ],
       [  1.        ,  30.        ,   0.        ,   0.        ,
         13.        ,   0.        ,   1.        ,   1.        ,
          0.        ],
       [  1.        ,   5.        ,   2.        ,   1.        ,
         19.2583    ,   0.        ,   0.        ,   0.        ,
          1.        ],
       [  0.        ,  29.69911765,   0.        ,   0.        ,
         26.        ,   0.        ,   1.        ,   0.        ,
          0.        ],
       [  0.        ,  51.        ,   0.        ,   1.        ,
         61.3792    ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,  32.        ,   0.        ,   0.        ,
         56.4958    ,   0.    

In [258]:
y_train

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

In [259]:
y_test

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0], dtype=int64)